language: dart

dart:
- dev

dart_task:
- test
- dartanalyzer

matrix:
include:
# analysis_options excludes don't work on stable
- dart: dev

# Only building master means that we don't run two builds for each pull request.
branches:
only: [master]