name: linkedin_login
description: Library for login with LinkedIn OAuth V2 service. This library helps you to implement authorization with LinkedIn OAuth API's.
version: 2.0.0-dev.2
homepage: https://github.com/d3xt3r2909/linkedin_login
repository: https://github.com/d3xt3r2909/linkedin_login
documentation:
  
environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.0-nullsafety.4
  http: ^0.13.0-nullsafety.0
  uuid: ^3.0.0-nullsafety.0
  meta: 1.3.0-nullsafety.6
  rxdart: 0.26.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0-nullsafety.17
  mockito: ^5.0.0-nullsafety.5

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/linked_in_logo.png
